import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter_24pt = localFont({
  src: [
    { path: "./fonts/Inter_24pt-Regular.woff2", weight: "400" },
    { path: "./fonts/Inter_24pt-Medium.woff2", weight: "500" },
    { path: "./fonts/Inter_24pt-SemiBold.woff2", weight: "600" },
    { path: "./fonts/Inter_24pt-Bold.woff2", weight: "700" },
    { path: "./fonts/Inter_24pt-Black.woff2", weight: "900" },
  ],
  variable: "--font-inter_24pt",
});

export const metadata: Metadata = {
  title: "Що є, чи нема",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ua">
      <body className={`${inter_24pt.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
